branches:
  only:
    - master
    - foolip/bikeshed
language: python
python:
  - "2.7"
install:
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable bikeshed
  - bikeshed update
script:
  - bikeshed spec
before_deploy:
  - rm index.bs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: foolip/bikeshed
