branches:
  only:
    - master
language: python
python:
  - "3.8"
install:
  - pip install bikeshed
  - bikeshed update
script:
  - bikeshed spec
before_deploy:
  - mkdir out
  - mv *.html *.png out/
deploy:
  local-dir: out
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
